export const Types = {
  RECUPERAR_PERSONAGENS_REQUEST: '[character]RECUPERAR_PERSONAGENS_REQUEST',
  RECUPERAR_PERSONAGENS_SUCCESS: '[character]RECUPERAR_PERSONAGENS_SUCCESS',
  RECUPERAR_PERSONAGENS_FAILURE: '[character]RECUPERAR_PERSONAGENS_FAILURE',
};
